// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  // Provide a clear console error to help diagnose "Failed to fetch" during auth
  // Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY will cause network failures.
  // Ensure a `.env` file with these keys exists or environment variables are set before running.
  // Example:
  // VITE_SUPABASE_URL=https://YOUR-PROJECT.supabase.co
  // VITE_SUPABASE_PUBLISHABLE_KEY=public-anon-key
  // eslint-disable-next-line no-console
  console.error(
    '[Supabase] Missing configuration: VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY are not set.'
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);